/**
 * Integration tests for the transcript pipeline.
 * Requires network access and yt-dlp on PATH.
 *
 * Run with: RUN_INTEGRATION=true bun test tests/integration/
 */
import { test, expect, describe } from "bun:test";
import { fetchTranscript, fetchVideoInfo } from "../../src/core/transcript.ts";

const RUN = Bun.env.RUN_INTEGRATION === "true";
const RICK_ASTLEY = "dQw4w9WgXcQ";

describe.skipIf(!RUN)("transcript integration", () => {
  test("fetches transcript for a known public video", async () => {
    const result = await fetchTranscript(RICK_ASTLEY, { cache: false });

    expect(result.videoId).toBe(RICK_ASTLEY);
    expect(result.language).toBe("en");
    expect(result.segments.length).toBeGreaterThan(10);
    expect(result.totalDuration).toBeGreaterThan(100);

    // Verify segment structure
    const first = result.segments[0]!;
    expect(typeof first.text).toBe("string");
    expect(first.text.length).toBeGreaterThan(0);
    expect(typeof first.startTime).toBe("number");
    expect(typeof first.endTime).toBe("number");
    expect(first.endTime).toBeGreaterThan(first.startTime);
  }, 30000);

  test("returns auto-generated caption flag", async () => {
    const result = await fetchTranscript(RICK_ASTLEY, { cache: false });
    // Rick Astley should have auto-generated or manual captions
    expect(typeof result.isAutoGenerated).toBe("boolean");
  }, 30000);

  test("fetches video info with metadata", async () => {
    const info = await fetchVideoInfo(RICK_ASTLEY);

    expect(info.id).toBe(RICK_ASTLEY);
    expect(info.title).toBeTruthy();
    expect(info.channel).toBeTruthy();
    expect(info.duration).toBeGreaterThan(100);
    expect(info.languages.length).toBeGreaterThan(0);
  }, 30000);
});
