import type { Command } from "commander";
import { parseVideoId } from "../utils/video-id.ts";
import { fetchTranscript, fetchVideoInfo } from "../core/transcript.ts";
import { formatTimestamp } from "../utils/timestamp.ts";
import { createSpinner, printSuccess, printError } from "../utils/progress.ts";
import type { TranscriptCommandOptions } from "../types/options.ts";

export function registerTranscriptCommand(program: Command): void {
  program
    .command("transcript")
    .description("Dump the raw transcript of a YouTube video")
    .requiredOption("-v, --video <id>", "YouTube video ID or URL")
    .option("-t, --timestamps", "Include timestamps", true)
    .option("-l, --lang <code>", "Transcript language code", "en")
    .option("--json", "Output as JSON array", false)
    .option("--chapters", "Group by video chapters if available", false)
    .option("--no-cache", "Skip cache")
    .action(async (opts: TranscriptCommandOptions & { cache?: boolean }) => {
      try {
        const { id } = parseVideoId(opts.video);

        const spinner = createSpinner(`Fetching transcript (${opts.lang ?? "en"})...`).start();
        const transcript = await fetchTranscript(id, {
          lang: opts.lang,
          cache: opts.cache,
        });
        spinner.succeed(
          `Transcript loaded (${transcript.segments.length} segments, ${transcript.isAutoGenerated ? "auto-generated" : "manual"})`
        );

        if (opts.json) {
          if (opts.chapters) {
            const info = await fetchVideoInfo(id);
            if (info.chapters.length > 0) {
              const grouped = info.chapters.map((ch) => ({
                chapter: ch.title,
                startTime: ch.startTime,
                segments: transcript.segments.filter(
                  (s) => s.startTime >= ch.startTime && s.startTime < ch.endTime
                ),
              }));
              console.log(JSON.stringify(grouped, null, 2));
              return;
            }
          }
          console.log(JSON.stringify(transcript.segments, null, 2));
        } else {
          // Text output
          if (opts.chapters) {
            const info = await fetchVideoInfo(id);
            if (info.chapters.length > 0) {
              for (const ch of info.chapters) {
                console.log(`\n## ${ch.title} [${formatTimestamp(ch.startTime)}]`);
                const chapterSegments = transcript.segments.filter(
                  (s) => s.startTime >= ch.startTime && s.startTime < ch.endTime
                );
                for (const seg of chapterSegments) {
                  if (opts.timestamps !== false) {
                    console.log(`[${formatTimestamp(seg.startTime)}] ${seg.text}`);
                  } else {
                    console.log(seg.text);
                  }
                }
              }
              return;
            }
          }

          for (const seg of transcript.segments) {
            if (opts.timestamps !== false) {
              console.log(`[${formatTimestamp(seg.startTime)}] ${seg.text}`);
            } else {
              console.log(seg.text);
            }
          }
        }
      } catch (err) {
        printError(err instanceof Error ? err.message : String(err));
        process.exit(1);
      }
    });
}
