import type { Command } from "commander";
import { parseVideoSource } from "../utils/video-source.ts";
import { fetchTranscript, fetchVideoInfo, loadTranscriptFile } from "../core/transcript.ts";
import { formatTimestamp } from "../utils/timestamp.ts";
import { createSpinner, printSuccess, printError } from "../utils/progress.ts";
import type { TranscriptCommandOptions } from "../types/options.ts";

export function registerTranscriptCommand(program: Command): void {
  program
    .command("transcript")
    .description(
      `Fetch and display the transcript of a video. No LLM call, no video download.

  Default output: timestamped text lines to stdout (one segment per line).
  Use --json to get a structured array of {text, startTime, endTime, duration} objects.
  Use --chapters to group output by chapter boundaries (if the video has them).

  Examples:
    llm-youtube transcript -v dQw4w9WgXcQ
    llm-youtube transcript -v dQw4w9WgXcQ --json
    llm-youtube transcript -v https://www.loom.com/share/abc123... --transcript-file captions.vtt
    llm-youtube transcript -v dQw4w9WgXcQ --json --chapters
    llm-youtube transcript -v dQw4w9WgXcQ --no-timestamps`
    )
    .requiredOption("-v, --video <id>", "YouTube video ID/URL or Loom share URL")
    .option("--transcript-file <path>", "Path to a local VTT or SRT transcript file (skips yt-dlp transcript fetch)")
    .option("-t, --timestamps", "Prefix each line with [M:SS] timestamp (default: true)", true)
    .option("-l, --lang <code>", "Transcript language code (default: en)", "en")
    .option("--json", "Output as JSON array of TranscriptSegment objects", false)
    .option("--chapters", "Group segments by chapter boundaries", false)
    .option("--no-cache", "Bypass cache and re-fetch")
    .action(async (opts: TranscriptCommandOptions & { cache?: boolean; transcriptFile?: string }) => {
      try {
        const source = parseVideoSource(opts.video);

        let transcript;
        if (opts.transcriptFile) {
          const spinner = createSpinner("Loading transcript file...").start();
          transcript = await loadTranscriptFile(opts.transcriptFile, `${source.platform}_${source.id}`);
          spinner.succeed(
            `Transcript loaded from file (${transcript.segments.length} segments)`
          );
        } else {
          const spinner = createSpinner(`Fetching transcript (${opts.lang ?? "en"})...`).start();
          transcript = await fetchTranscript(source, {
            lang: opts.lang,
            cache: opts.cache,
          });
          spinner.succeed(
            `Transcript loaded (${transcript.segments.length} segments, ${transcript.isAutoGenerated ? "auto-generated" : "manual"})`
          );
        }

        if (opts.json) {
          if (opts.chapters) {
            const info = await fetchVideoInfo(source);
            if (info.chapters.length > 0) {
              const grouped = info.chapters.map((ch) => ({
                chapter: ch.title,
                startTime: ch.startTime,
                segments: transcript.segments.filter(
                  (s) => s.startTime >= ch.startTime && s.startTime < ch.endTime
                ),
              }));
              console.log(JSON.stringify(grouped, null, 2));
              return;
            }
          }
          console.log(JSON.stringify(transcript.segments, null, 2));
        } else {
          // Text output
          if (opts.chapters) {
            const info = await fetchVideoInfo(source);
            if (info.chapters.length > 0) {
              for (const ch of info.chapters) {
                console.log(`\n## ${ch.title} [${formatTimestamp(ch.startTime)}]`);
                const chapterSegments = transcript.segments.filter(
                  (s) => s.startTime >= ch.startTime && s.startTime < ch.endTime
                );
                for (const seg of chapterSegments) {
                  if (opts.timestamps !== false) {
                    console.log(`[${formatTimestamp(seg.startTime)}] ${seg.text}`);
                  } else {
                    console.log(seg.text);
                  }
                }
              }
              return;
            }
          }

          for (const seg of transcript.segments) {
            if (opts.timestamps !== false) {
              console.log(`[${formatTimestamp(seg.startTime)}] ${seg.text}`);
            } else {
              console.log(seg.text);
            }
          }
        }
      } catch (err) {
        printError(err instanceof Error ? err.message : String(err));
        process.exit(1);
      }
    });
}
