export interface TranscriptSegment {
  text: string;
  startTime: number; // seconds (float)
  endTime: number; // seconds (float)
  duration: number; // seconds (float)
}

export interface TranscriptResult {
  videoId: string;
  language: string;
  segments: TranscriptSegment[];
  totalDuration: number;
  isAutoGenerated: boolean;
}

export interface TranscriptOptions {
  lang?: string;
  cache?: boolean;
}

export interface Chapter {
  title: string;
  startTime: number;
  endTime: number;
}

export interface VideoInfo {
  id: string;
  title: string;
  channel: string;
  duration: number;
  uploadDate: string;
  viewCount: number;
  description: string;
  languages: string[];
  chapters: Chapter[];
  thumbnailUrl?: string;
  url: string;
  platform: string;
}
