import { $ } from "bun";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { mkdir, readdir, rm } from "node:fs/promises";
import type {
  TranscriptResult,
  TranscriptSegment,
  TranscriptOptions,
  VideoInfo,
  Chapter,
} from "../types/transcript.ts";
import { Cache } from "../utils/cache.ts";

/**
 * Fetch transcript for a YouTube video via yt-dlp.
 */
export async function fetchTranscript(
  videoId: string,
  options: TranscriptOptions = {}
): Promise<TranscriptResult> {
  const lang = options.lang ?? "en";
  const cache = new Cache();

  // Check cache first
  if (options.cache !== false) {
    const cached = await cache.getTranscript(videoId, lang);
    if (cached) return cached;
  }

  const tempDir = join(tmpdir(), `llm-youtube-${videoId}-${Date.now()}`);
  await mkdir(tempDir, { recursive: true });

  try {
    const url = `https://www.youtube.com/watch?v=${videoId}`;

    // Try auto-generated subs first, then manual
    await $`yt-dlp --write-auto-sub --write-sub --sub-lang ${lang} --sub-format vtt --skip-download -o ${join(tempDir, "%(id)s")} ${url}`
      .quiet()
      .nothrow();

    // Find the VTT file
    const files = await readdir(tempDir);
    const vttFile = files.find((f) => f.endsWith(".vtt"));

    if (!vttFile) {
      // List available languages
      const langResult =
        await $`yt-dlp --list-subs ${url}`.quiet().nothrow();
      const langOutput = langResult.stdout.toString();

      throw new Error(
        `No transcript available in '${lang}'\n` +
          `Available languages can be found with: llm-youtube info -v ${videoId}\n` +
          (langOutput.includes("Available subtitles")
            ? `\nSubtitle info:\n${langOutput}`
            : "")
      );
    }

    const vttContent = await Bun.file(join(tempDir, vttFile)).text();
    const isAutoGenerated = vttFile.includes(".auto.") || vttFile.includes("a.");
    const segments = parseVtt(vttContent);
    const deduped = deduplicateSegments(segments);

    const totalDuration =
      deduped.length > 0 ? deduped[deduped.length - 1]!.endTime : 0;

    const result: TranscriptResult = {
      videoId,
      language: lang,
      segments: deduped,
      totalDuration,
      isAutoGenerated,
    };

    // Cache the result
    if (options.cache !== false) {
      await cache.setTranscript(videoId, lang, result);
    }

    return result;
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}

/**
 * Fetch video metadata via yt-dlp --dump-json.
 */
export async function fetchVideoInfo(videoId: string): Promise<VideoInfo> {
  const url = `https://www.youtube.com/watch?v=${videoId}`;

  const result = await $`yt-dlp --dump-json --skip-download ${url}`.quiet();
  const data = JSON.parse(result.stdout.toString());

  const chapters: Chapter[] = (data.chapters ?? []).map(
    (ch: { title: string; start_time: number; end_time: number }) => ({
      title: ch.title,
      startTime: ch.start_time,
      endTime: ch.end_time,
    })
  );

  // Collect available subtitle languages
  const languages: string[] = [];
  if (data.subtitles) {
    languages.push(...Object.keys(data.subtitles));
  }
  if (data.automatic_captions) {
    for (const lang of Object.keys(data.automatic_captions)) {
      if (!languages.includes(lang)) {
        languages.push(lang);
      }
    }
  }

  return {
    id: videoId,
    title: data.title ?? "Unknown",
    channel: data.channel ?? data.uploader ?? "Unknown",
    duration: data.duration ?? 0,
    uploadDate: data.upload_date ?? "",
    viewCount: data.view_count ?? 0,
    description: data.description ?? "",
    languages,
    chapters,
    thumbnailUrl: data.thumbnail,
  };
}

/**
 * Parse WebVTT content into TranscriptSegments.
 */
function parseVtt(vttContent: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const lines = vttContent.split("\n");

  let i = 0;
  // Skip header
  while (i < lines.length && !lines[i]!.includes("-->")) {
    i++;
  }

  while (i < lines.length) {
    const line = lines[i]!.trim();

    if (line.includes("-->")) {
      const [startStr, endStr] = line.split("-->").map((s) => s.trim());
      if (!startStr || !endStr) {
        i++;
        continue;
      }

      const startTime = vttTimeToSeconds(startStr);
      const endTime = vttTimeToSeconds(endStr);

      // Collect text lines
      i++;
      const textLines: string[] = [];
      while (i < lines.length && lines[i]!.trim() !== "" && !lines[i]!.includes("-->")) {
        // Strip VTT tags like <c>, </c>, <00:00:01.000>
        const cleaned = lines[i]!
          .replace(/<[^>]+>/g, "")
          .trim();
        if (cleaned) textLines.push(cleaned);
        i++;
      }

      const text = textLines.join(" ").trim();
      if (text) {
        segments.push({
          text,
          startTime,
          endTime,
          duration: endTime - startTime,
        });
      }
    } else {
      i++;
    }
  }

  return segments;
}

function vttTimeToSeconds(timeStr: string): number {
  // Format: HH:MM:SS.mmm or MM:SS.mmm
  const parts = timeStr.split(":");
  if (parts.length === 3) {
    return (
      parseFloat(parts[0]!) * 3600 +
      parseFloat(parts[1]!) * 60 +
      parseFloat(parts[2]!)
    );
  } else if (parts.length === 2) {
    return parseFloat(parts[0]!) * 60 + parseFloat(parts[1]!);
  }
  return parseFloat(timeStr);
}

/**
 * Deduplicate overlapping auto-generated caption segments.
 * Merges segments with >80% text overlap.
 */
function deduplicateSegments(
  segments: TranscriptSegment[]
): TranscriptSegment[] {
  if (segments.length === 0) return [];

  const result: TranscriptSegment[] = [segments[0]!];

  for (let i = 1; i < segments.length; i++) {
    const current = segments[i]!;
    const prev = result[result.length - 1]!;

    const overlap = textOverlap(prev.text, current.text);
    if (overlap > 0.8) {
      // Merge: keep the longer text, extend the time range
      if (current.text.length > prev.text.length) {
        prev.text = current.text;
      }
      prev.endTime = Math.max(prev.endTime, current.endTime);
      prev.duration = prev.endTime - prev.startTime;
    } else {
      result.push(current);
    }
  }

  return result;
}

function textOverlap(a: string, b: string): number {
  const wordsA = new Set(a.toLowerCase().split(/\s+/));
  const wordsB = new Set(b.toLowerCase().split(/\s+/));
  const intersection = new Set([...wordsA].filter((w) => wordsB.has(w)));
  const union = new Set([...wordsA, ...wordsB]);
  return union.size === 0 ? 0 : intersection.size / union.size;
}
