import { test, expect, describe } from "bun:test";
import {
  alignFramesWithTranscript,
  segmentTranscript,
} from "../../src/core/alignment.ts";
import type { TranscriptResult, TranscriptSegment, Chapter } from "../../src/types/transcript.ts";
import type { ExtractedFrame } from "../../src/types/frame.ts";

// Helper to create transcript segments
function seg(text: string, start: number, end: number): TranscriptSegment {
  return { text, startTime: start, endTime: end, duration: end - start };
}

// Helper to create frames
function frame(ts: number, index: number = 0): ExtractedFrame {
  return {
    index,
    timestamp: ts,
    timestampFormatted: `${Math.floor(ts / 60)}m${Math.floor(ts % 60)}s`,
    filePath: `/tmp/frame_${index}.png`,
    method: "scene",
  };
}

const sampleTranscript: TranscriptResult = {
  videoId: "test123",
  language: "en",
  segments: [
    seg("Welcome to the intro.", 0, 5),
    seg("Let's talk about topic one.", 5, 10),
    seg("This is important context.", 10, 15),
    seg("Now moving to topic two.", 60, 65),
    seg("Topic two has many details.", 65, 70),
    seg("Here's a key insight.", 70, 75),
    seg("Finally topic three.", 120, 125),
    seg("Wrapping up now.", 125, 130),
  ],
  totalDuration: 130,
  isAutoGenerated: false,
};

describe("alignFramesWithTranscript", () => {
  test("maps frames to correct transcript segments by timestamp", () => {
    const frames = [frame(3, 0), frame(62, 1), frame(122, 2)];
    const chapters: Chapter[] = [
      { title: "Intro", startTime: 0, endTime: 60 },
      { title: "Topic Two", startTime: 60, endTime: 120 },
      { title: "Topic Three", startTime: 120, endTime: 130 },
    ];

    const result = alignFramesWithTranscript(frames, sampleTranscript, chapters);

    expect(result.segments).toHaveLength(3);
    expect(result.segments[0]!.frames).toHaveLength(1);
    expect(result.segments[0]!.frames[0]!.timestamp).toBe(3);
    expect(result.segments[1]!.frames).toHaveLength(1);
    expect(result.segments[1]!.frames[0]!.timestamp).toBe(62);
    expect(result.segments[2]!.frames).toHaveLength(1);
    expect(result.segments[2]!.frames[0]!.timestamp).toBe(122);
  });

  test("handles segments with no frames", () => {
    const frames = [frame(3, 0)]; // only in first segment
    const chapters: Chapter[] = [
      { title: "Intro", startTime: 0, endTime: 60 },
      { title: "Topic Two", startTime: 60, endTime: 120 },
    ];

    const result = alignFramesWithTranscript(frames, sampleTranscript, chapters);

    expect(result.segments[0]!.frames).toHaveLength(1);
    expect(result.segments[1]!.frames).toHaveLength(0);
  });

  test("handles frames with no matching transcript", () => {
    // Frame at timestamp 50 — there's a gap in transcript (15-60)
    const frames = [frame(50, 0)];
    const chapters: Chapter[] = [
      { title: "Intro", startTime: 0, endTime: 60 },
    ];

    const result = alignFramesWithTranscript(frames, sampleTranscript, chapters);

    // Frame still maps to the segment by time range
    expect(result.segments[0]!.frames).toHaveLength(1);
  });

  test("respects chapter boundaries when available", () => {
    const frames = [frame(3, 0), frame(62, 1)];
    const chapters: Chapter[] = [
      { title: "Part One", startTime: 0, endTime: 60 },
      { title: "Part Two", startTime: 60, endTime: 130 },
    ];

    const result = alignFramesWithTranscript(frames, sampleTranscript, chapters);

    expect(result.segments[0]!.chapterTitle).toBe("Part One");
    expect(result.segments[1]!.chapterTitle).toBe("Part Two");
  });

  test("returns correct metadata", () => {
    const frames = [frame(3, 0), frame(62, 1)];
    const chapters: Chapter[] = [
      { title: "Intro", startTime: 0, endTime: 60 },
      { title: "Body", startTime: 60, endTime: 130 },
    ];

    const result = alignFramesWithTranscript(frames, sampleTranscript, chapters);

    expect(result.videoId).toBe("test123");
    expect(result.frameCount).toBe(2);
    expect(result.segmentCount).toBe(2);
    expect(result.totalDuration).toBe(130);
  });
});

describe("segmentTranscript", () => {
  test("uses chapters when provided", () => {
    const chapters: Chapter[] = [
      { title: "A", startTime: 0, endTime: 60 },
      { title: "B", startTime: 60, endTime: 130 },
    ];

    const result = segmentTranscript(sampleTranscript.segments, 130, chapters);

    expect(result).toHaveLength(2);
    expect(result[0]!.title).toBe("A");
    expect(result[1]!.title).toBe("B");
  });

  test("detects topic shifts via vocabulary when no chapters", () => {
    const result = segmentTranscript(sampleTranscript.segments, 130);

    // Should create at least one segment
    expect(result.length).toBeGreaterThanOrEqual(1);
    // First segment starts at 0
    expect(result[0]!.startTime).toBe(0);
    // Last segment ends at total duration
    expect(result[result.length - 1]!.endTime).toBe(130);
  });

  test("splits on long pauses between segments", () => {
    // Our sample has gaps at 15-60 and 75-120
    const result = segmentTranscript(sampleTranscript.segments, 130);

    // Should detect the large gaps as boundaries
    expect(result.length).toBeGreaterThanOrEqual(2);
  });

  test("returns single segment for very short content", () => {
    const shortSegments = [seg("Hello world.", 0, 5)];
    const result = segmentTranscript(shortSegments, 5);

    expect(result).toHaveLength(1);
    expect(result[0]!.startTime).toBe(0);
    expect(result[0]!.endTime).toBe(5);
  });
});
